{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocelotgw.config-map.fullname" . }}
  labels:
    {{- include "ocelotgw.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.avp }}
data:
  appsettings.json: |-
    {
       "CORS": {
        "Origins": {{ required "A valid .Values.config.cors.origins entry required!" .Values.config.cors.origins | quote }}
      },
      "Logging": {
        "LogLevel": {
          "Default": "Information"
        }
      },
      "AllowedHosts": {{ required "A valid .Values.config.allowedHosts entry required!" .Values.config.allowedHosts | quote }}
    }
{{- end }}