{{- if .Values.enabled -}}
{{- $cfgname  := include "ocelotgw.config-map.fullname" . -}}
{{- $ocgname  := include "ocelotgw.ocelot-config.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "ocelotgw.fullname" . }}
  labels:
    {{- include "ocelotgw.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.avp }}
spec:
{{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount | default 1 }}
{{- end }}
  selector:
    matchLabels:
      {{- include "ocelotgw.selectorLabels" . | nindent 6 }}
  template:
    metadata:
    {{- with .Values.podAnnotations }}
      annotations:
        checksum/config: {{ $cfgname | sha256sum }}
        {{- toYaml . | nindent 8 }}        
    {{- end }}
      labels:
        {{- include "ocelotgw.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "ocelotgw.serviceAccountName" . }}
      automountServiceAccountToken: {{ .Values.automountServiceAccountToken | default false }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "tbsazdevacr.azurecr.io/ocelot/api:v1.2"
          imagePullPolicy: IfNotPresent
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP

          volumeMounts:
          - name: config-ocelot
            mountPath: /app/ocelot.json
            subPath: ocelot.json
          - name: config-vol
            mountPath: /app/appsettings.json
            subPath: appsettings.json

          livenessProbe:
            httpGet:
              path: {{ .Values.deployment.probes.path }} 
              port: {{ .Values.deployment.probes.port }} 
            initialDelaySeconds: {{ .Values.deployment.probes.initDelay | default 60 }}
            periodSeconds: {{ .Values.deployment.probes.period | default 10 }}
          
          readinessProbe:
            httpGet:
              path: {{ .Values.deployment.probes.path }} 
              port: {{ .Values.deployment.probes.port }} 
            initialDelaySeconds: {{ .Values.deployment.probes.initDelay | default 60 }}
            periodSeconds: {{ .Values.deployment.probes.period | default 10 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      
      volumes:
      - name: config-vol
        configMap:
          name: {{ $cfgname }}
      - name: config-ocelot
        configMap:
          name: {{ $ocgname }} 

      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}