{{- if .Values.enabled -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ocelotgw.ocelot-config.fullname" . }}
  labels:
    {{- include "ocelotgw.labels" . | nindent 4 }}
  annotations:
    avp.kubernetes.io/path: {{ .Values.avp }}
data: 
    ocelot.json: |-
        {
            "Routes": [
                {
                    "DownstreamPathTemplate":   {{ required "A valid .Values.config.ocelot.downstreamPathTemplate entry required!" .Values.config.ocelot.downstreamPathTemplate | quote }} ,
                    "DownstreamScheme":         {{ required "A valid .Values.config.ocelot.downStreamScheme entry required!"       .Values.config.ocelot.downStreamScheme | quote }} ,
                    "DownstreamHostAndPorts": [
                            {
                                "Host": {{ required "A valid .Values.config.ocelot.downStreamHost entry required!" .Values.config.ocelot.downStreamHost | quote }} ,
                                "Port": {{ required "A valid .Values.config.ocelot.downStreamPort entry required!" .Values.config.ocelot.downStreamPort | quote }} 
                            }
                        ],                    
                    "UpstreamPathTemplate":      {{ required "A valid .Values.config.ocelot.upstreamPathTemplate entry required!" .Values.config.ocelot.upstreamPathTemplate | quote }} ,
                    "UpstreamHttpMethod": [ "Get", "Post", "Put", "Delete", "OPTIONS" ]                   
                }
            ],
            "GlobalConfiguration": {
                "RateLimitOptions": {
                    "QuotaExceededMessage": "لا يمكن اتخاذ نفس الاجراء أكثر من مره .",
                    "HttpStatusCode": 429
                }
            }
        }
{{- end }}